spring.application.name=restaurant
spring.datasource.url=jdbc:h2:mem:restaurantdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=1234
spring.h2.console.enabled=true
spring.sql.init.mode=always
server.port=8069
spring.data.redis.host=redis-10800.crce202.eu-west-3-1.ec2.cloud.redislabs.com
spring.data.redis.port=10800
spring.data.redis.password=eX1Obky4Ofuzo6eE2oi7h4KnSTEfuDgf
spring.data.redis.username=default
spring.cache.redis.time-to-live=120000
spring.cache.type=redis