spring.application.name=restaurant
spring.datasource.url=jdbc:h2:mem:restaurantdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=1234
spring.h2.console.enabled=true
spring.sql.init.mode=always
